### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by Hauru427** [Hauru427/Mary-s-todo-list#56]
お世話になっております。
卒業試験のMVPリリース依頼です。
お忙しいところ恐れ入りますが、ご確認お願いいたします。

## 各種情報
サービス名：Merry's todoリスト
サービスURL：https://merystodo-80a52780b2d3.herokuapp.com
等を記載してください

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] ログアウト機能
- [x] タスク管理機能（追加・編集・削除）
- [x] Linebot用いた機能
- [x] タスク通知機能
- [x] メリーさんからのメッセージ機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
なければこの項目は省略してください

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

**Comment by ippei-shimizu** [comment]
下記機能について確認ができませんでした。
ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

--- 

> Linebot用いた機能
> タスク通知機能
> メリーさんからのメッセージ機能

コメントに記載があった上記の機能を確認するための動線が見当たりませんでした。
お手数ですがご確認のほどよろしくお願いいたします。

**Comment by Hauru427** [comment]
説明不足で申し訳ございません。
そちらの機能に関しては、LINEログインしたユーザーかつタスクに期限を設定したもののみ通知を送信する設定にしています。

トップページのLogin with lineよりログイン
[![Image from Gyazo](https://i.gyazo.com/2ad1069e01d5494e92d8e01c9c3164c0.png)](https://gyazo.com/2ad1069e01d5494e92d8e01c9c3164c0)

その後タスクを作成し、期限を設定するとlineが送信されます。
下記はlineのテスト通知を行った時の画像です。
[![Image from Gyazo](https://i.gyazo.com/5526cc55318e290791db418b2ea5a754.png)](https://gyazo.com/5526cc55318e290791db418b2ea5a754)

送信するタイミングについては現状下記に設定しています。
1日1回送信
期限前のタスク（3日前、2日前、1日前、1時間前）
期限切れのタスク　（1日後、2日後、3日後）

以上、お手数ですがご確認のほどよろしくお願いいたします。

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
上記共有いただきありがとうございます。LINEログイン後に「リスト作成」を押下して、ページ遷移いたしました。
<img width="721" alt="スクリーンショット 2024-07-05 19 16 39" src="https://github.com/Hauru427/Mary-s-todo-list/assets/108249057/083b49a2-ae47-4062-882c-ecfe02c6cbd4">
こちら記入できるものが「Title」しかないのですが、URL等合っていますでしょうか？
ご確認の上もう一度提出してください。

**Comment by Hauru427** [comment]
ご確認いただきありがとうございます。
Githubのプロジェクトのようなイメージにしたいと思ったのでリストを作成後にカードを追加できるようにしています。
詳細は下記の動画をご確認お願いいたします。
https://github.com/Hauru427/Mary-s-todo-list/assets/151431516/159bdec1-e8f9-437b-87dc-96b1209cdea9

最初の導線が分かりにくいと思ってはいたので、本リリースまでにあらかじめ「進行中、完了」といったリストは作成してあるように変更するつもりです。

以上、お手数ですがご確認のほどお願いいたします。

**Comment by tarakish** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
